/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Program;

import static Program.dataPengembalian.kodeBuku;
import java.sql.*;
import koneksi.koneksi;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author Kyyyy
 */
public class masukAkun extends javax.swing.JFrame {
    private Connection conn = new koneksi().getkoneksi();
    public static String idPetugas;
    
    public static String getIdPetugas(){
        return idPetugas;
    }
    /**
     * Creates new form masukAkun
     */
    public masukAkun(){
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKeluar = new javax.swing.JLabel();
        inputNamaAkun = new javax.swing.JTextField();
        inputKataSandi = new javax.swing.JPasswordField();
        btnMasukAkun = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconsWhite/iconCancel.png"))); // NOI18N
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });
        getContentPane().add(btnKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1290, 40, -1, -1));

        inputNamaAkun.setBackground(new java.awt.Color(238, 235, 221));
        inputNamaAkun.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        inputNamaAkun.setForeground(new java.awt.Color(50, 56, 70));
        inputNamaAkun.setBorder(null);
        getContentPane().add(inputNamaAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 361, 262, 45));

        inputKataSandi.setBackground(new java.awt.Color(238, 235, 221));
        inputKataSandi.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        inputKataSandi.setForeground(new java.awt.Color(50, 56, 70));
        inputKataSandi.setBorder(null);
        getContentPane().add(inputKataSandi, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 458, 262, 45));

        btnMasukAkun.setBackground(new java.awt.Color(255, 255, 255));
        btnMasukAkun.setFont(new java.awt.Font("Poppins Medium", 0, 13)); // NOI18N
        btnMasukAkun.setForeground(new java.awt.Color(50, 56, 70));
        btnMasukAkun.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMasukAkun.setText("Masuk Akun");
        btnMasukAkun.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMasukAkun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasukAkunMouseClicked(evt);
            }
        });
        getContentPane().add(btnMasukAkun, new org.netbeans.lib.awtextra.AbsoluteConstraints(538, 538, 286, 40));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/masukAkun.png"))); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMasukAkunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasukAkunMouseClicked
        // TODO add your handling code here:
         String user="", pass="";
            user = inputNamaAkun.getText();
            pass = inputKataSandi.getText();
        
        try{
            String sql = "SELECT * FROM petugas WHERE nama_akun='"+user+"' AND kata_sandi='"+pass+"'";
            java.sql.Statement stat= conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            
            if(user.equals("") && pass.equals("")){
                JOptionPane.showMessageDialog(this, "Tolong isi nama akun dan password anda");
            }else if(user.equals("") && !(pass.equals(""))){
                JOptionPane.showMessageDialog(this, "Tolong isi nama akun anda");
            }else if(!(user.equals("")) && pass.equals("")){
                JOptionPane.showMessageDialog(this, "Tolong isi password anda");
            }
            else{
                if(hasil.next()){
                    if(user.equals(user) && pass.equals(pass)){
                        JOptionPane.showMessageDialog(null, "Anda Berhasil Login");
                        idPetugas = hasil.getString("kode_petugas");
                        prosesPeminjaman.kodepetugas.setText(hasil.getString(1));
                        beranda.namaPetugas.setText(hasil.getString(2));
                        beranda.namaAkun.setText(hasil.getString(4));
                        new beranda().setVisible(true);
                        this.setVisible(false);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Nama akun atau kata sandi anda salah!");
    //                    inputNamaAkun.setText("");
    //                    inputKataSandi.setText("");
                    inputNamaAkun.requestFocus(true);
                }
            }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Koneksi Database Gagal");
        }
    }//GEN-LAST:event_btnMasukAkunMouseClicked

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Apakah anda ingin keluar aplikasi?","Konfirmasi",JOptionPane.YES_NO_CANCEL_OPTION);
        if(ok == 0){
            dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Anda tidak keluar aplikasi");
        }
    }//GEN-LAST:event_btnKeluarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masukAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masukAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masukAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masukAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masukAkun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnKeluar;
    private javax.swing.JLabel btnMasukAkun;
    private javax.swing.JPasswordField inputKataSandi;
    private javax.swing.JTextField inputNamaAkun;
    // End of variables declaration//GEN-END:variables
}
